---
# tasks file for openldap
- name: Installing openldap
  apt:
    pkg:
      - slapd
      - ldap-utils
    state: present
  become: yes
- name: reconfigure openldap
  shell:
    dpkg-reconfigure slapd
  become: yes
  args:
    warn: false # set warn=false to prevent warning
