---
# tasks file for virtualenv
- stat: path={{ virtualenv_dir }}
  register: virtualenv_dir_exists

- name: Permissões no diretório /opt
  command: chown -R {{ usuario_terminal }}:{{ usuario_terminal }} /opt
  become: yes
  args:
    warn: false # set warn=false to prevent warning

- name: Removing {{ virtualenv_dir }}
  file:
    path: '{{ virtualenv_dir }}'
    state: absent
    force: yes

- name: create app directory
  file:
    path: '{{ app_dir }}'
    state: directory

- name: create app requirements file
  file:
    path: '{{ app_dir }}/requirements.txt'
    state: touch

# create a directory if it doesn't exist
- name: Create '{{ virtualenv_dir }}' if it doesn't exist
  file:
    path: '{{ virtualenv_dir }}'
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"
    owner: '{{ usuario_terminal }}'
    group: '{{ usuario_terminal }}'

- name: Install virtualenv package
  with_items: [ setuptools, pip ]
  pip:
    name: virtualenv
    executable: pip

- name: Create virtualenv "{{ virtualenv_dir }}/python3_test_app"
  pip:
    virtualenv: "{{ virtualenv_dir }}/test_app"
    virtualenv_python: python3.7
    requirements: "{{ app_dir }}/requirements.txt"

- name: u=rwx,g=rwx,o=r for '{{ virtualenv_dir }}/python3_test_app' dir
  file:
    path: '{{ virtualenv_dir }}/test_app'
    state: directory
    owner: '{{ usuario_terminal }}'
    group: '{{ usuario_terminal }}'
    mode: "u=rwx,g=rwx,o=r"

