---
# tasks file for oracle-java
- name: Adding Java 12 PPA
  apt_repository: "repo='{{ item }}'"
  with_items:
    - "ppa:linuxuprising/java"
  become: yes      

- name: Set Java JDK license as accepted
  debconf: name='oracle-java12-installer' question='shared/accepted-oracle-license-v1-2' value='true' vtype='select'
  become: yes

- name: Installing Java 12
  apt:
    pkg:
      - oracle-java12-installer
      - oracle-java12-set-default
    state: present
  become: yes

