---
# tasks file for graphical_tools
- name: Install Inkscape (Snap)
  command: snap install inkscape --classic
  become: yes

- name: Install Gimp (Snap)
  command: snap install gimp --classic
  become: yes

- name: Install Freemind (Snap)
  command: snap install freemind --classic
  become: yes

- name: Installing Graphical Apps
  apt:
    pkg:
      - glabels
    state: present
  become: yes
