---
# tasks file for flask_environment
- name: disable lighttpd as service To avoid conflicts with nginx
  systemd: 
    name=lighttpd 
    state=stopped 
    enabled=no
  become: yes
  register: lighttpd_disable
  ignore_errors: True

- name: Disable Apache2 as service To avoid conflicts with nginx
  service:
    name=apache2
    state=stopped
    enabled=no
  become: yes
  register: apache2_disable
  ignore_errors: True

- name: Installing Python
  apt:
    pkg:
      - tree         # Optional
      - python-pip   # Optional
      - python-dev   # Optional
      - python3-pip
      - python3-dev
      - python3-setuptools
      - build-essential
      - libssl-dev
      - libffi-dev
      - nginx
    state: present
  become: yes

- name: Install virtualenv package
  with_items: [ setuptools, pip ]
  pip:
    name: virtualenv
    executable: pip

- name: create {{ virtualenv_dir }} directory if they don't exist
  file:
    path: "{{ virtualenv_dir }}"
    state: directory
    owner: "{{ usuario_terminal }}"
    group: "{{ usuario_terminal }}"
    mode: 0775

- name: setting /opt dir permissions
  command: chown -R {{ usuario_terminal }}:{{ usuario_terminal }} /opt
  become: yes
  args:
    warn: false # set warn=false to prevent warning

- name: open firewall for nginx
  ufw:
    rule: allow
    name: Nginx Full

- name: open firewall for 5000 port
  ufw:
    rule: allow
    port: 5000

- name: clone hello world repo
  git:
    repo: 'https://github.com/rodrigosantosbr/flask-hello-world.git'
    dest: /opt/flask-hello-world
    update: yes  # Does a git pull if the repo already exists
  
- name: install modules in a virtualenv
  pip:
    requirements: /opt/flask-hello-world/requirements.txt
    virtualenv: "{{ virtualenv_dir }}/flask-hello-world"
    virtualenv_python: python3.7

- name: virtualenv activate
  shell: "source {{ virtualenv_dir }}/flask-hello-world/bin/activate"

- name: execute python
  shell: "python /opt/flask-hello-world/app.py"

#- name: restart nginx
#  systemd: name=nginx state=restarted enabled=yes
  
