---
# tasks file for flask_environment
- name: disable lighttpd as service To avoid conflicts with nginx
  systemd: 
    name=lighttpd 
    state=stopped 
    enabled=no
  become: yes

- name: Disable Apache as service To avoid conflicts with nginx
  service:
    name=apache2
    state=stopped
    enabled=no
  become: yes

- name: Installing Python
  apt:
    pkg:
      - tree         # Optional
      - python-pip   # Optional
      - python-dev   # Optional
      - python3-pip
      - python3-dev
      - nginx
    state: present
  become: yes

  - name: clone hello world repo
    git:
      repo: 'https://github.com/rodrigosantosbr/flask-hello-world.git'
      dest: /opt/flask-hello-world
      update: yes  # Does a git pull if the repo already exists
  
  - name: install modules in a virtualenv
    pip:
      requirements: /opt/flask-hello-world/requirements.txt
      virtualenv: /home/{{ ansible_ssh_user }}/{{ app_name }}/env
      virtualenv_python: python3.5
