---
# Setup/install tasks.
# dpkg-query -W mysql-server -> 5.7.26-0ubuntu0.19.04.1
- name: Installing mysql
  apt:
    pkg:
      - python-mysqldb
      - python3-mysqldb
      - mysql-common
      - mysql-server
    state: present
  become: yes
  register: mysql_installation

# Because Ubuntu starts MySQL as part of the install process, we need to stop
# mysql and remove the logfiles in case the user set a custom log file size.
- name: Ensure MySQL is stopped after initial install.
  service: "name={{ mysql_daemon }} state=stopped"
  when: mysql_installation is success

- name: Delete innodb log files created by apt package after initial install.
  file: path={{ mysql_datadir }}/{{item}} state=absent
  with_items:
    - "ib_logfile0"
    - "ib_logfile1"
  when: mysql_installation is success

# Configure MySQL.
- include_tasks: configure.yml
#- include_tasks: secure-installation.yml
#- include_tasks: databases.yml
#- include_tasks: users.yml
#- include_tasks: replication.yml
