---
# tasks file for utilities
- name: Installing Utilities
  apt:
    pkg:
      - aptitude
      - build-essential
      - network-manager
      # C compiler
      - cpp
      - cmake
      - gcc
      - g++
      - g++-7
      # terminal apps
      - tree
      - whois
      - ldap-utils
      - samba
      - ubuntu-restricted-extras
      - xclip
      # Fonts
      - ttf-ubuntu-font-family
      - fonts-ubuntu-font-family-console
      - ppa-purge
    state: present
  become: yes

