---
# tasks file for docker
- name: Configuring Docker
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - gnupg-agent
      - software-properties-common
      - docker
      - wmdocker
    state: present
  become: yes
  when: ansible_architecture == "x86_64"
