---
# tasks file for docker
- name: Configuring Docker
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - docker
      - wmdocker
    state: present
  become: yes
  when: ansible_architecture == "x86_64"
