---
# tasks file for docker
- name: Installing prerequisites
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - gnupg-agent
      - software-properties-common
      - docker
      - wmdocker
    state: present
  become: yes
  when: ansible_architecture == "x86_64"

- name: Remove "docker" old versions
  apt:
    pkg: 
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Add an Apt signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu
    state: present
