---
# tasks file for docker
- name: Installing prerequisites
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - gnupg-agent
      - software-properties-common
      - docker
      - wmdocker
    state: present
  become: yes
  when: ansible_architecture == "x86_64"

- name: Remove "docker" old versions
  apt:
    pkg: 
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
      - docker-ce
    state: absent

- name: Add an Apt Docker signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_architecture == "x86_64"

- name: Add Docker Repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu disco test
    state: present
  when: ansible_architecture == "x86_64"

- name: apt-get update
  apt: update_cache=yes
  become: yes # root
  
- name: Install Docker packages
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  when: ansible_architecture == "x86_64"
