---

# this playbook does reconfiguration of Ubuntu 19.04 machine
# ansible-playbook /etc/ansible/playbooks/01_ubuntu_1904_initial.yaml

- name: Executar as instalações e configuracoes no localhost
  hosts: local
  become: yes
  vars_prompt:
    - name: "utilities_user_answer"
      prompt: "Install Utilities (True/False)?"
      private: no
      default: true
    - name: "graphical_user_answer"
      prompt: "Install Graphical Tools like Gimp, Inkscape (True/False)?"
      private: no
      default: true
    - name: "browser_user_answer"
      prompt: "Install Browsers like Chromium, Opera (True/False)?"
      private: no
      default: true
    - name: "productivity_user_answer"
      prompt: "Install Productivity Tools like Skype, Keepassx, Dropbox, Mailspring (True/False)?"
      private: no
      default: true
    - name: "maintenance_user_answer"
      prompt: "Install Maintenance Tools (True/False)?"
      private: no
      default: true
    - name: "chrony_user_answer"
      prompt: "Install Chrony (True/False)?"
      private: no
      default: true
    - name: "user_answer"
      prompt: "Proceed (True/False)?"
      private: no
      default: true
  pre_tasks:
    - name: Add Canonical Partners Repository into sources list
      apt_repository:
        repo: 'deb http://archive.canonical.com/ {{ansible_distribution_release | lower}} partner'
        state: present
      when:
        ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool
    - name: Add multiverse Repository into sources list
      apt_repository:
        repo: 'deb http://archive.canonical.com/ubuntu {{ansible_distribution_release | lower}} multiverse'
        state: present
      when:
        ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool
    - name: apt-get update
      apt: update_cache=yes
      become: yes # root
      when:
        ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool
    - name: apt-get upgrade
      apt: upgrade=yes
      become: yes
      when:
        ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool
  roles:
    - { role: utilities, 
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool and utilities_user_answer|bool }
    - { role: graphical_tools, 
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool and graphical_user_answer|bool }
    - { role: browsers, 
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool and browser_user_answer|bool }
    - { role: productivity, 
        when: ansible_distribution == 'Ubuntu'and ansible_distribution_version == '19.04' and user_answer | bool and productivity_user_answer|bool }
    - { role: maintenance, 
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool and maintenance_user_answer|bool }
    - { role: chrony, 
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool and chrony_user_answer|bool }
  tasks:
    - debug: "msg=ansible_connection:{{ansible_connection}}"
    - debug: "msg=user_answer:{{user_answer}}"
    - debug: "msg=distro_name:{{ansible_distribution_release | lower}}"
    - pause: seconds=3
