---

# this playbook does reconfiguration of Ubuntu 19.04 machine
# ansible-playbook /etc/ansible/playbooks/02_ubuntu_1904_dev_apps.yaml

- name: Executar as instalações e configuracoes no localhost
  hosts: local
  become: yes
  vars_prompt:
    - name: "java_user_answer"
      prompt: "Install Oracle Java compiler (true/false)?"
      private: no
      default: true
    - name: "flash_user_answer"
      prompt: "Install Adobe Flash (true/false)?"
      private: no
      default: true
    - name: "c_user_answer"
      prompt: "Configure C/C++ environment (true/false)?"
      private: no
      default: true
    - name: "pascal_user_answer"
      prompt: "Configure Pascal environment (true/false)?"
      private: no
      default: false
    - name: "python_user_answer"
      prompt: "Configure Python environment (true/false)?"
      private: no
      default: true
    - name: "ruby_user_answer"
      prompt: "Configure Ruby environment (true/false)?"
      private: no
      default: false
    - name: "dotnet_user_answer"
      prompt: "Configure Dotnet environment (true/false)?"
      private: no
      default: false
    - name: "php_user_answer"
      prompt: "Configure PHP 7.2 environment (true/false)?"
      private: no
      default: true
    - name: "phpmyadmin_user_answer"
      prompt: "Configure PHPmyAdmin environment (true/false)?"
      private: no
      default: true
    - name: "lua_user_answer"
      prompt: "Configure Lua 5.3 environment (true/false)?"
      private: no
      default: true
    - name: "git_user_answer"
      prompt: "Install GIT (true/false)?"
      private: no
      default: true
    - name: "ide_user_answer"
      prompt: "Install IDEs - Sublime / Atom / Brackets / VSCode / Pycharm (true/false)?"
      private: no
      default: true
    - name: "user_answer"
      prompt: "Proceed (true/false)?"
      private: no
      default: true
  pre_tasks:
    - name: apt-get update
      apt: update_cache=yes
      become: yes # root
      when:
        ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool
    - name: Ensure Python 2 is installed
      apt:
        name: 
          - python2
          - python2.7
        state: present
    - name: Installing Essential Dev Packages
      apt:
        pkg:
          - curl
          - freetds-dev
          - gdebi
          - gconf-service
          - gconf-service-backend
          - gconf2
          - gconf2-common
          - gfortran
          - m4
          - ispell
          - meld
          - memcached
          - numlockx
          - net-tools
          - libssl-dev
          - shared-mime-info
      become: yes
      when:
        ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool
  roles:
    - { role: adobe-flash, 
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool and flash_user_answer|bool }
    - { role: c-c++, 
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool and c_user_answer|bool }
    - { role: dotnet,
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool and dotnet_user_answer|bool }
    - { role: git, 
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool and git_user_answer|bool }
    - { role: oracle-java, 
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool and java_user_answer|bool }
    - { role: python, 
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool and python_user_answer|bool }
    - { role: pascal, 
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool and pascal_user_answer|bool }
    - { role: ruby, 
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool and ruby_user_answer|bool }
    - { role: php, 
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool and php_user_answer|bool }
    - { role: phpmyadmin, 
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool and phpmyadmin_user_answer|bool }
    - { role: lua, 
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool and lua_user_answer|bool }
    - { role: devops-ides, 
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool and ide_user_answer|bool }

