---

# this playbook does configuration of zsh on ubuntu machine
# ansible-playbook /etc/ansible/playbooks/03_ubuntu_1904_zsh.yaml

- name: Executar as instalações e configuracoes do ZSH
  hosts: local
  become: yes
  vars_prompt:
    - name: "user_answer"
      prompt: "Proceed (true/false)?"
      private: no
      default: true
  pre_tasks:
    - name: apt-get update
      apt: update_cache=yes
      become: yes # root
      when:
        ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool
    - name: apt-get upgrade
      apt: upgrade=yes
      become: yes
      when:
        ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool
  roles:
    - { role: zsh, when: ansible_distribution == 'Ubuntu' and user_answer | bool }
  tasks:

