---

# this playbook does reconfiguration of Ubuntu 19.04 machine
# ansible-playbook /etc/ansible/playbooks/02_ubuntu_1904_dev_apps.yaml

- name: Executar as instalações e configuracoes no localhost
  hosts: local
  become: yes
  vars_prompt:
    - name: "flash_user_answer"
      prompt: "Install Adobe Flash (true/false)?"
      private: no
      default: true
    - name: "ruby_user_answer"
      prompt: "Configure Ruby environment (true/false)?"
      private: no
      default: false
    - name: "php_user_answer"
      prompt: "Configure PHP 7.2 environment (true/false)?"
      private: no
      default: true
    - name: "phpmyadmin_user_answer"
      prompt: "Configure PHPmyAdmin environment (true/false)?"
      private: no
      default: false
    - name: "nodejs_user_answer"
      prompt: "Configure Nodejs environment (true/false)?"
      private: no
      default: true
    - name: "golang_user_answer"
      prompt: "Configure Golang environment (true/false)?"
      private: no
      default: true
    - name: "ide_user_answer"
      prompt: "Install IDEs - Sublime / Atom / Brackets / VSCode / Pycharm (true/false)?"
      private: no
      default: false
    - name: "user_answer"
      prompt: "Proceed (true/false)?"
      private: no
      default: true
  pre_tasks:
    - name: apt-get update
      apt: update_cache=yes
      become: yes # root
      when:
        - ansible_distribution == 'Ubuntu' 
          and ansible_distribution_version == '19.04' 
          and user_answer | bool
      tags: apt_update
    - name: Ensure Python 2 is installed
      apt:
        name: 
          - python2
          - python2.7
        state: present
  roles:
    - { role: adobe-flash, 
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool and flash_user_answer|bool }
    - { role: ruby, 
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool and ruby_user_answer|bool }
    - { role: php, 
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool and php_user_answer|bool }
    - { role: phpmyadmin, 
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool and phpmyadmin_user_answer|bool }
    - { role: devops-ides,
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool and ide_user_answer|bool }
    - { role: nodejs,
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool and nodejs_user_answer|bool }
    - { role: golang,
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool and golang_user_answer|bool }
