- name: Executar as instalações e configuracoes no localhost
  hosts: local
  become: yes
  vars_prompt:
    - name: "user_answer"
      prompt: "Proceed (True/False)?"
      private: no
      default: true
  pre_tasks:
    - name: apt-get update
      apt: update_cache=yes
      become: yes # root
      when:
        ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool
    - name: apt-get upgrade
      apt: upgrade=yes
      become: yes
      when:
        ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool
  roles:
    - { role: geerlingguy.apache, become: yes,
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool }
    - { role: php, 
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool }
    - { role: geerlingguy.mysql, become: yes,
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool }

