---

# this playbook does reconfiguration of virtualenv on ubuntu 19.04 dev machine
# ansible-playbook -K 5_virtualenv.yml

- name: Executar as instalações e configuracoes do virtualenv
  hosts: local
  become: yes
  vars_prompt:
    - name: "user_answer"
      prompt: "Proceed (true/false)?"
      private: no
      default: true
  pre_tasks:
    - name: apt-get update
      apt: update_cache=yes
      become: yes # root
      when:
        ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool
    - name: Ensure Python 2 is installed
      apt:
        name: 
          - python2
          - python2.7
        state: present
  roles:
    - { role: virtualenv, 
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool }

