---

# this playbook does reconfiguration of Web Servers on ubuntu 19.04 dev machine
# ansible-playbook /etc/ansible/playbooks/12_ubuntu1904_webservers.yaml

- name: Executar as instalações e configuracoes do Webserver
  hosts: local
  become: yes
  vars_prompt:
    - name: "apache2_user_answer"
      prompt: "Install Apache2 (true/false)?"
      private: no
      default: true
    - name: "nginx_user_answer"
      prompt: "Install Nginx (true/false)?"
      private: no
      default: true
    - name: "gunicorn_user_answer"
      prompt: "Install Gunicorn (true/false)?"
      private: no
      default: true
    - name: "user_answer"
      prompt: "Proceed (true/false)?"
      private: no
      default: true
  pre_tasks:
    - name: apt-get update
      apt: update_cache=yes
      become: yes # root
      when:
        ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' and user_answer | bool
      tags: apt_update
    - name: Ensure Python 2 is installed
      apt:
        name: 
          - python2
          - python2.7
        state: present
      tags: python2_check
  roles:
    - { role: geerlingguy.apache, 
        when: 
          ansible_distribution == 'Ubuntu' 
          and ansible_distribution_version == '19.04'
          and user_answer | bool
          and apache2_user_answer | bool }
    - { role: nginx, 
        when: 
          ansible_distribution == 'Ubuntu' 
          and ansible_distribution_version == '19.04' 
          and user_answer | bool
          and nginx_user_answer | bool }
    - { role: gunicorn, 
        when: 
          ansible_distribution == 'Ubuntu' 
          and ansible_distribution_version == '19.04' 
          and user_answer | bool
          and gunicorn_user_answer | bool }

