---
# tasks file for email_communication
- name: Installing Email & Communication apps
  apt:
    pkg:
      - thunderbird
      - pidgin
      - evolution
    state: present
  become: yes

- name: Install Skype (Snap)
  command: snap install skype --classic
  become: yes

- name: Install MailSpring (Snap)
  command: snap install mailspring --classic
  become: yes
