---
# tasks file for freebasic
- name: Install libtinfo5
  apt:
    pkg:
      - libtinfo5
    state: present
  become: yes

- name: Download freebasic.tar.gz on /tmp
  get_url:
    url: https://downloads.sourceforge.net/project/fbc/Binaries%20-%20Linux/FreeBASIC-1.06.0-linux-x86_64.tar.gz?r=&ts=1561493045
    dest: /tmp/freebasic.tar.gz
  when:
    ansible_distribution == "Ubuntu" and ansible_distribution_version == "19.04"

- name: Extract freebasic.tar.gz into /tmp
  unarchive:
    src: /tmp/freebasic.tar.gz
    dest: /tmp
